import { expect, test } from '@jest/globals';
import { matching } from '../matchingFunction';

const confirmedMentors = [
  {
    usersId: 4,
    usersRoleId: 3,
    usersCountryId: 'AUS',
    usersMaxCapacity: 7,
    userMentorUniversityBackgrounds: [
      {
        id: 4,
        userId: 4,
        studylevel: 1,
        attendanceType: 2,
        universityId: 21,
        subjectId: 38,
      },
      {
        id: 13,
        userId: 4,
        studylevel: 2,
        attendanceType: 2,
        universityId: 7,
        subjectId: 31,
      },
      {
        id: 22,
        userId: 4,
        studylevel: 3,
        attendanceType: 1,
        universityId: 4,
        subjectId: 21,
      },
    ],
  },
  {
    usersId: 6,
    usersRoleId: 3,
    usersCountryId: 'CAN',
    usersMaxCapacity: 8,
    userMentorUniversityBackgrounds: [
      {
        id: 6,
        userId: 6,
        studylevel: 3,
        attendanceType: 1,
        universityId: 10,
        subjectId: 30,
      },
      {
        id: 15,
        userId: 6,
        studylevel: 2,
        attendanceType: 1,
        universityId: 8,
        subjectId: 51,
      },
      {
        id: 24,
        userId: 6,
        studylevel: 1,
        attendanceType: 3,
        universityId: 12,
        subjectId: 46,
      },
    ],
  },
  {
    usersId: 2,
    usersRoleId: 3,
    usersCountryId: 'CAN',
    usersMaxCapacity: 8,
    userMentorUniversityBackgrounds: [
      {
        id: 2,
        userId: 2,
        studylevel: 3,
        attendanceType: 1,
        universityId: 6,
        subjectId: 57,
      },
      {
        id: 11,
        userId: 2,
        studylevel: 1,
        attendanceType: 3,
        universityId: 17,
        subjectId: 36,
      },
      {
        id: 20,
        userId: 2,
        studylevel: 3,
        attendanceType: 3,
        universityId: 11,
        subjectId: 65,
      },
      {
        id: 29,
        userId: 2,
        studylevel: 1,
        attendanceType: 3,
        universityId: 5,
        subjectId: 5,
      },
    ],
  },
  {
    usersId: 9,
    usersRoleId: 3,
    usersCountryId: 'FRA',
    usersMaxCapacity: 5,
    userMentorUniversityBackgrounds: [
      {
        id: 9,
        userId: 9,
        studylevel: 2,
        attendanceType: 2,
        universityId: 14,
        subjectId: 3,
      },
      {
        id: 18,
        userId: 9,
        studylevel: 1,
        attendanceType: 3,
        universityId: 24,
        subjectId: 41,
      },
      {
        id: 27,
        userId: 9,
        studylevel: 3,
        attendanceType: 2,
        universityId: 9,
        subjectId: 4,
      },
    ],
  },
  {
    usersId: 7,
    usersRoleId: 3,
    usersCountryId: 'GBR',
    usersMaxCapacity: 6,
    userMentorUniversityBackgrounds: [
      {
        id: 7,
        userId: 7,
        studylevel: 2,
        attendanceType: 2,
        universityId: 30,
        subjectId: 45,
      },
      {
        id: 16,
        userId: 7,
        studylevel: 3,
        attendanceType: 1,
        universityId: 33,
        subjectId: 71,
      },
      {
        id: 25,
        userId: 7,
        studylevel: 1,
        attendanceType: 1,
        universityId: 31,
        subjectId: 67,
      },
    ],
  },
  {
    usersId: 3,
    usersRoleId: 3,
    usersCountryId: 'GBR',
    usersMaxCapacity: 6,
    userMentorUniversityBackgrounds: [
      {
        id: 3,
        userId: 3,
        studylevel: 1,
        attendanceType: 3,
        universityId: 13,
        subjectId: 15,
      },
      {
        id: 12,
        userId: 3,
        studylevel: 3,
        attendanceType: 1,
        universityId: 28,
        subjectId: 85,
      },
      {
        id: 21,
        userId: 3,
        studylevel: 1,
        attendanceType: 1,
        universityId: 3,
        subjectId: 61,
      },
      {
        id: 30,
        userId: 3,
        studylevel: 3,
        attendanceType: 1,
        universityId: 1,
        subjectId: 78,
      },
    ],
  },
  {
    usersId: 1,
    usersRoleId: 3,
    usersCountryId: 'USA',
    usersMaxCapacity: 5,
    userMentorUniversityBackgrounds: [
      {
        id: 1,
        userId: 1,
        studylevel: 2,
        attendanceType: 3,
        universityId: 16,
        subjectId: 75,
      },
      {
        id: 10,
        userId: 1,
        studylevel: 3,
        attendanceType: 2,
        universityId: 2,
        subjectId: 47,
      },
      {
        id: 19,
        userId: 1,
        studylevel: 1,
        attendanceType: 2,
        universityId: 27,
        subjectId: 34,
      },
      {
        id: 28,
        userId: 1,
        studylevel: 2,
        attendanceType: 1,
        universityId: 22,
        subjectId: 32,
      },
    ],
  },
  {
    usersId: 5,
    usersRoleId: 3,
    usersCountryId: 'FRA',
    usersMaxCapacity: 5,
    userMentorUniversityBackgrounds: [
      {
        id: 5,
        userId: 5,
        studylevel: 2,
        attendanceType: 1,
        universityId: 18,
        subjectId: 82,
      },
      {
        id: 14,
        userId: 5,
        studylevel: 1,
        attendanceType: 3,
        universityId: 25,
        subjectId: 89,
      },
      {
        id: 23,
        userId: 5,
        studylevel: 2,
        attendanceType: 2,
        universityId: 19,
        subjectId: 63,
      },
    ],
  },
  {
    usersId: 8,
    usersRoleId: 3,
    usersCountryId: 'AUS',
    usersMaxCapacity: 7,
    userMentorUniversityBackgrounds: [
      {
        id: 8,
        userId: 8,
        studylevel: 1,
        attendanceType: 3,
        universityId: 23,
        subjectId: 70,
      },
      {
        id: 17,
        userId: 8,
        studylevel: 2,
        attendanceType: 2,
        universityId: 26,
        subjectId: 79,
      },
      {
        id: 26,
        userId: 8,
        studylevel: 2,
        attendanceType: 3,
        universityId: 15,
        subjectId: 64,
      },
    ],
  },
];

const userWithUniversityApplication = {
  usersId: 14,
  usersRoleId: 6,
  usersCountryId: 'ITA',
  userMenteeUniversityApplications: [
    {
      id: 5,
      userId: 14,
      studylevel: 3,
      firstUniversityId: 8,
      firstSubjectId: 25,
      secondUniversityId: 23,
      secondSubjectId: 12,
      thirdUniversityId: 30,
      thirdSubjectId: 54,
      bestMentorMatches: null,
    },
  ],
};

const userUniversityApplicationOnly = {
  id: 5,
  userId: 14,
  studylevel: 3,
  firstUniversityId: 8,
  firstSubjectId: 25,
  secondUniversityId: 23,
  secondSubjectId: 12,
  thirdUniversityId: 30,
  thirdSubjectId: 54,
  bestMentorMatches: null,
};

const topThreeMentors = [
  {
    menteeUserId: 14,
    mentorUserId: 8,
    studylevelMatch: 0,
    originCountryMatch: 0,
    menteeUniOneMatch: 0,
    menteeUniTwoMatch: 30,
    menteeUniThreeMatch: 0,
    menteeSubjectOneMatch: 0,
    menteeSubjectTwoMatch: 0,
    menteeSubjectThreeMatch: 0,
    finalSum: 30,
  },
  {
    menteeUserId: 14,
    mentorUserId: 6,
    studylevelMatch: 10,
    originCountryMatch: 0,
    menteeUniOneMatch: 30,
    menteeUniTwoMatch: 0,
    menteeUniThreeMatch: 0,
    menteeSubjectOneMatch: 0,
    menteeSubjectTwoMatch: 0,
    menteeSubjectThreeMatch: 0,
    finalSum: 40,
  },
  {
    menteeUserId: 14,
    mentorUserId: 7,
    studylevelMatch: 10,
    originCountryMatch: 0,
    menteeUniOneMatch: 0,
    menteeUniTwoMatch: 0,
    menteeUniThreeMatch: 30,
    menteeSubjectOneMatch: 0,
    menteeSubjectTwoMatch: 0,
    menteeSubjectThreeMatch: 0,
    finalSum: 40,
  },
];

test('checkTopThreeMentors', () => {
  const result = matching(
    confirmedMentors,
    userWithUniversityApplication,
    userUniversityApplicationOnly,
  );
  expect(result).toStrictEqual(topThreeMentors);
});
